version: "3"

services:
  client:
    container_name: auth-client
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    networks:
      - auth
    depends_on:
      - server
  server:
    container_name: auth-server
    ports:
      - "3001:3000"
    build:
      context: ./server
    volumes:
      - ./server:/app
    links:
      - mongo
    networks:
      - auth
    depends_on:
      - mongo
  mongo:
    container_name: auth-db
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"
    networks:
      - auth
  nginx:
    container_name: auth-router
    build:
      context: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - client
      - server
      - mongo
    networks:
      - auth

networks:
  auth:
    driver: bridge